# Generated by Django 5.1.3 on 2024-11-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=144)),
                ('mobile_no', models.CharField(max_length=12)),
                ('date_of_birth', models.CharField(max_length=144)),
                ('email', models.CharField(max_length=144)),
                ('password', models.CharField(max_length=144)),
                ('date', models.DateField()),
            ],
        ),
    ]
