# Generated by Django 5.1.3 on 2024-12-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=144)),
                ('password', models.CharField(max_length=144)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='login',
        ),
    ]
